### ISSUE TITLE
Unable to send requests.

### ISSUE THREAD

**Issue by boomramada** [Apipa169/Assistant-Relay-for-Hassio#62]
I have got docker version of assistant relay installed as follows:
`docker run -d --name assistant_relay \
  -p 3030:3030 \
  -v $(pwd)/config.json:/data/config.json:rw \
  -v $(pwd)/audio-responses:/data/audio-responses:rw \
  apipa169/armv7-hassio-assistant_relay:latest
`
Using the port 3030 instead of 3000, which is already updated on config.json.

But when I'm running it, getting following errors:

`
0|www  | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases
0|www  | TypeError: Cannot read property 'getRequestHeaders' of undefined
0|www  |     at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32)
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:219:5
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:166:5
`
I have followed the https://assistantrelay.com/docs/getting-started/configuration and created the users.

And in HA,  I got following set:

`
rest_command:
  assistant_broadcast:
    method: POST
    url: 'http://IP:3030/assistant'    
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"usr", "broadcast":true}'
    verify_ssl: false
    
  assistant_converse:
    method: POST
    url: 'http://IP:3030/assistant'
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"usr", "converse":true}'
    verify_ssl: false

  assistant_relay:
    method: POST
    url: 'http://IP:3030/assistant'
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"usr"}'
    verify_ssl: false
`

And when I try to send a message, I get following error:
2021-01-08 11:34:30 ERROR (MainThread) [homeassistant.components.rest_command] Client error http://IP:3030/assistant

**Comment by pickonedev** [comment]
Same here

**Comment by pickonedev** [comment]
I manage to solve the problem, You must go to google console and ENABLE google assistant API

**Comment by boomramada** [comment]
My  Google Assistant API was enable and still getting following errors
`

0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5),
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:219:5,
0|www  |     at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32),
0|www  | TypeError: Cannot read property '0' of undefined

`

**Comment by mzelmanovich** [comment]
Same here

**Comment by spicerackk** [comment]
> My Google Assistant API was enable and still getting following errors
> 
> 0|www | at processTicksAndRejections (internal/process/task_queues.js:93:5),
> 0|www | at /assistant_relay/node_modules/grpc/src/credentials.js:219:5,
> 0|www | at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32),
> 0|www | TypeError: Cannot read property '0' of undefined
> 
> When I'm creating the Credentials, unser OAuth client ID, I had to select Web Application instead of Other. As there was no Other.

I get exactly the same errors, and also had to select Web Application instead of Other which doesn't exist in the drop down.

**Comment by ALERTua** [comment]
try http://IP:3030/api/assistant
