### ISSUE TITLE
Commands no longer work: "TypeError: Cannot read property 'converse' of undefined"

### ISSUE THREAD

**Issue by robtesch** [Apipa169/Assistant-Relay-for-Hassio#68]
**Describe the bug**
Commands of any kind no longer work (They used to work flawlessly for over a year). By "no longer work" I mean they don't do anything. No broadcast is made at all.

**To Reproduce**
Any of the ways you can use this addon do not work (and give the same error). I have tried using the sandbox, the developer tools, automations, everything. I've also tried using two different google users (both linked at different times, and both previously working).

**Expected behavior**
Expecting the commands to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/30407321/108692888-1995f680-74f5-11eb-8b68-aa2f935f9864.png)

**System (please complete the following information):**
Hassio version: core-2021.2.3
System: supervisor-2021.02.11

**Additional context**
Error message is as follows:

```
POST /server/getResponses 200 33.363 ms - 380
0|www  | POST /server/getConfig 200 36.489 ms - 124
0|www  | POST /server/getConfig 200 33.912 ms - 124
0|www  | POST /server/getConfig 200 32.903 ms - 124
0|www  | GET /server/users 304 32.557 ms - -
0|www  | POST /server/getConfig 200 31.834 ms - 124
0|www  | POST /server/checkUpdate 200 488.019 ms - 1189
0|www  | v3.2.0
0|www  | GET /server/version 200 33.326 ms - 20
0|www  | POST /server/getResponses 200 36.175 ms - 380
0|www  | POST /server/getConfig 200 31.904 ms - 124
0|www  | GET /server/users 304 32.980 ms - -
0|www  | POST /server/getConfig 200 20.206 ms - 124
0|www  | TypeError: Cannot read property 'converse' of undefined
0|www  |     at new Conversation (/assistant_relay/node_modules/google-assistant/components/conversation.js:136:34)
0|www  |     at /assistant_relay/helpers/assistant.js:19:38
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by spicerackk** [comment]
I have a similar issue, where I get this:

```0|www  | TypeError: Cannot read property '0' of undefined
0|www  |     at exports.setCredentials (/assistant_relay/helpers/auth.js:41:97)
0|www  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|www  |     at async /assistant_relay/helpers/server.js:60:36
0|www  | Assistant Relay Server Initialized
0|www  | Visit http://172.30.33.4:3000 in a browser to configure
0|www  | An update is available. Please visit https://github.com/greghesp/assistant-relay/releases
0|www  | TypeError: Cannot read property 'getRequestHeaders' of undefined
0|www  |     at getAuthorizationHeaderFromGoogleCredential (/assistant_relay/node_modules/grpc/src/credentials.js:188:32)
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:219:5
0|www  |     at /assistant_relay/node_modules/grpc/src/credentials.js:166:5
```

**Comment by robtesch** [comment]
Seems that updating to the latest supervisor (supervisor-2021.02.11) which wasn't available at the time of the bug report has solved my issue. Closing.
